"""receipt item quantity

Revision ID: 45fb604e74cc
Revises: 981bd366121b
Create Date: 2026-08-31 21:49:57.064374+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '45fb604e74cc'
down_revision: str | None = '981bd366121b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Existing rows predate this column; every one of them is a single item.
    # Backfill with a server default, then drop the default so new writes must
    # say what the quantity actually is.
    op.add_column(
        'receipt_items',
        sa.Column('quantity', sa.Integer(), nullable=False, server_default='1'),
    )
    op.alter_column('receipt_items', 'quantity', server_default=None)
    op.create_check_constraint('ck_quantity_positive', 'receipt_items', 'quantity >= 1')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_quantity_positive', 'receipt_items', type_='check')
    op.drop_column('receipt_items', 'quantity')
    # ### end Alembic commands ###
